function init() {
    set_progress();
    set_question();
    document.getElementById("results_button").disabled = true;
    document.getElementById("results_button").style.visibility = 'hidden';    
}

function skip() {
    scores += "-1";
    if (index < length) {
        index++;
        set_progress();
        set_question();
    }
    else {
        results();
    }
}

function next() {
    update_scores();
    if (index < length) {
        answered++;
        index++;
        set_progress();
        set_question();
    }
    else {
        results();
    }
}

function slider_update() {
    var value = document.getElementById("slider").value;
    document.getElementById("right_precentage").innerHTML = value + "%";
    document.getElementById("left_precentage").innerHTML = 100-value + "%";
}

function set_progress() {
    document.getElementById("progress").innerHTML = "Question " + index + " out of " + length;
}

function set_question() {
    document.getElementById("left_trait").innerHTML = measures[index][0];
    document.getElementById("right_trait").innerHTML = measures[index][1];
    document.getElementById("slider").value = "50";
    slider_update();
    if (answered == minimum) {
        document.getElementById("results_button").disabled = false;
        document.getElementById("results_button").style.visibility = 'visible';    
    }
}

function update_scores() {
    var val = document.getElementById("slider").value;
    if (val == 100) {
        scores += "--";
    }
    else if (val < 10) {
        scores += "0" + val;
    }
    else {
        scores += val;
    }
}

function results() {
    location.href = "results.html?a=" + scores;
}

window.onload = init;
var index = 1;
var length = 400;
var answered = 0;
var minimum = 20;
var scores = "";

var measures = {
    1: ["playful", "serious"],
    2: ["shy", "bold"],
    3: ["cheery", "sorrowful"],
    4: ["masculine", "feminine"],
    5: ["charming", "awkward"],
    6: ["lewd", "tasteful"],
    7: ["intellectual", "physical"],
    8: ["strict", "lenient"],
    9: ["refined", "rugged"],
    10: ["trusting", "suspicious"],
    11: ["innocent", "worldly"],
    12: ["artistic", "scientific"],
    13: ["stoic", "expressive"],
    14: ["cunning", "honorable"],
    15: ["orderly", "chaotic"],
    16: ["normal", "weird"],
    17: ["competitive", "cooperative"],
    18: ["tense", "relaxed"],
    19: ["brave", "careful"],
    20: ["spiritual", "skeptical"],
    21: ["unlucky", "fortunate"],
    22: ["ferocious", "pacifist"],
    23: ["modest", "flamboyant"],
    24: ["dominant", "submissive"],
    25: ["forgiving", "vengeful"],
    26: ["wise", "foolish"],
    27: ["impulsive", "cautious"],
    28: ["loyal", "traitorous"],
    29: ["creative", "conventional"],
    30: ["curious", "apathetic"],
    31: ["rude", "respectful"],
    32: ["diligent", "lazy"],
    33: ["lustful", "chaste"],
    34: ["chatty", "reserved"],
    35: ["emotional", "logical"],
    36: ["moody", "stable"],
    37: ["dunce", "genius"],
    38: ["arrogant", "humble"],
    39: ["heroic", "villainous"],
    40: ["attractive", "repulsive"],
    41: ["rational", "whimsical"],
    42: ["mischievous", "well behaved"],
    43: ["aloof", "obsessed"],
    44: ["indulgent", "sober"],
    45: ["kinky", "vanilla"],
    46: ["straightforward", "cryptic"],
    47: ["spontaneous", "deliberate"],
    48: ["libertarian", "socialist"],
    49: ["scheduled", "spontaneous"],
    50: ["works hard", "plays hard"],
    51: ["reasoned", "instinctual"],
    52: ["focused on the present", "focused on the future"],
    53: ["empirical", "theoretical"],
    54: ["open", "guarded"],
    55: ["methodical", "astonishing"],
    56: ["mighty", "puny"],
    57: ["bossy", "meek"],
    58: ["barbaric", "civilized"],
    59: ["gregarious", "private"],
    60: ["quiet", "loud"],
    61: ["political", "nonpolitical"],
    62: ["confident", "insecure"],
    63: ["democratic", "authoritarian"],
    64: ["debased", "pure"],
    65: ["fast", "slow"],
    66: ["frugal", "lavish"],
    67: ["ludicrous", "sensible"],
    68: ["orange", "purple"],
    69: ["tall", "short"],
    70: ["young", "old"],
    71: ["down2earth", "head@clouds"],
    72: ["extrovert", "introvert"],
    73: ["open to new experinces", "uncreative"],
    74: ["calm", "anxious"],
    75: ["disorganized", "self-disciplined"],
    76: ["quarrelsome", "warm"],
    77: ["nerd", "jock"],
    78: ["lowbrow", "highbrow"],
    79: ["selfish", "altruistic"],
    80: ["autistic", "neurotypical"],
    81: ["angelic", "demonic"],
    82: ["hesitant", "decisive"],
    83: ["devout", "heathen"],
    84: ["cruel", "kind"],
    85: ["direct", "roundabout"],
    86: ["mathematical", "literary"],
    87: ["blue-collar", "ivory-tower"],
    88: ["slovenly", "stylish"],
    89: ["playful", "shy"],
    90: ["serious", "bold"],
    91: ["charming", "trusting"],
    92: ["awkward", "suspicious"],
    93: ["hipster", "basic"],
    94: ["coordinated", "clumsy"],
    95: ["funny", "humorless"],
    96: ["politically correct", "edgy"],
    97: ["rich", "poor"],
    98: ["hard", "soft"],
    99: ["remote", "involved"],
    100: ["metaphorical", "literal"],
    101: ["biased", "impartial"],
    102: ["mundane", "extraordinary"],
    103: ["tirewsome", "interesting"],
    104: ["smooth", "rough"],
    105: ["spicy", "mild"],
    106: ["enslaved", "emancipated"],
    107: ["optimistic", "pessimistic"],
    108: ["sickly", "healthy"],
    109: ["luddite", "technophile"],
    110: ["vain", "demure"],
    111: ["high-tech", "low-tech"],
    112: ["flexible", "rigid"],
    113: ["cosmopolitan", "provincial"],
    114: ["arcane", "mainstream"],
    115: ["outlaw", "sheriff"],
    116: ["pronatalist", "child free"],
    117: ["sad", "happy"],
    118: ["jealous", "compersive"],
    119: ["bitter", "sweet"],
    120: ["resigned", "resistant"],
    121: ["sarcastic", "genuine"],
    122: ["human", "animalistic"],
    123: ["sporty", "bookish"],
    124: ["moderate", "extreme"],
    125: ["angry", "good-humored"],
    126: ["depressed", "bright"],
    127: ["self-conscious", "self-assured"],
    128: ["vulnerable", "armoured"],
    129: ["warm", "cold"],
    130: ["assertive", "passive"],
    131: ["active", "slothful"],
    132: ["imaginative", "practical"],
    133: ["adventurous", "stick-in-the-mud"],
    134: ["obedient", "rebellious"],
    135: ["competent", "incompetent"],
    136: ["unambitious", "driven"],
    137: ["simple", "complicated"],
    138: ["proletariat", "bourgeoisie"],
    139: ["alpha", "beta"],
    140: ["'right-brained'", "'left-brained'"],
    141: ["thick-skinned", "sensitive"],
    142: ["charismatic", "uninspiring"],
    143: ["feisty", "gracious"],
    144: ["eloquent", "unpolished"],
    145: ["high IQ", "low IQ"],
    146: ["insider", "outsider"],
    147: ["morning lark", "night owl"],
    148: ["thin", "thick"],
    149: ["sheeple", "conspiracist"],
    150: ["neat", "messy"],
    151: ["vague", "precise"],
    152: ["philosophical", "real"],
    153: ["modern", "historical"],
    154: ["judgemental", "accepting"],
    155: ["average", "deviant"],
    156: ["gossiping", "confidential"],
    157: ["official", "backdoor"],
    158: ["scholarly", "crafty"],
    159: ["leisurely", "hurried"],
    160: ["explorer", "builder"],
    161: ["captain", "first-mate"],
    162: ["mysterious", "unambiguous"],
    163: ["independent", "codependent"],
    164: ["family-first", "work-first"],
    165: ["scruffy", "manicured"],
    166: ["wild", "tame"],
    167: ["prestigious", "disreputable"],
    168: ["scandalous", "proper"],
    169: ["unprepared", "hoarder"],
    170: ["sheltered", "street-smart"],
    171: ["open-minded", "close-minded"],
    172: ["permanent", "transient"],
    173: ["dramatic", "no-nonsense"],
    174: ["apprentice", "master"],
    175: ["straight", "queer"],
    176: ["androgynous", "gendered"],
    177: ["repetitive", "varied"],
    178: ["patient", "impatient"],
    179: ["poisonous", "nurturing"],
    180: ["creepy", "disarming"],
    181: ["inspiring", "cringeworthy"],
    182: ["soulless", "soulful"],
    183: ["hard", "soft"],
    184: ["beautiful", "ugly"],
    185: ["domestic", "industrial"],
    186: ["juvenile", "mature"],
    187: ["idealist", "realist"],
    188: ["nihilist", "existentialist"],
    189: ["objective", "subjective"],
    190: ["theist", "atheist"],
    191: ["classical", "avant-garde"],
    192: ["utilitarian", "decorative"],
    193: ["generalist", "specialist"],
    194: ["multicolored", "monochrome"],
    195: ["complimentary", "insulting"],
    196: ["individualist", "communal"],
    197: ["equitable", "hypocritical"],
    198: ["traditional", "unorthodox"],
    199: ["workaholic", "slacker"],
    200: ["resourceful", "helpless"],
    201: ["crazy", "sane"],
    202: ["anarchist", "statist"],
    203: ["cool", "dorky"],
    204: ["important", "irrelevant"],
    205: ["noob", "pro"],
    206: ["deranged", "reasonable"],
    207: ["rural", "urban"],
    208: ["introspective", "not introspective"],
    209: ["city-slicker", "country-bumpkin"],
    210: ["western", "eastern"],
    211: ["mad", "glad"],
    212: ["social", "reclusive"],
    213: ["studious", "goof-off"],
    214: ["slugabed", "go-getter"],
    215: ["penny-pincher", "overspender"],
    216: ["liberal", "conservative"],
    217: ["unassuming", "pretentious"],
    218: ["persistent", "quitter"],
    219: ["hedonist", "monastic"],
    220: ["patriotic", "unpatriotic"],
    221: ["tactful", "indiscreet"],
    222: ["wholesome", "salacious"],
    223: ["joyful", "miserable"],
    224: ["zany", "regular"],
    225: ["alert", "oblivious"],
    226: ["feminist", "sexist"],
    227: ["racist", "egalitarian"],
    228: ["abstract", "concrete"],
    229: ["formal", "intimate"],
    230: ["resolute", "wavering"],
    231: ["deep", "shallow"],
    232: ["valedictorian", "drop out"],
    233: ["minimalist", "pack rat"],
    234: ["trash", "treasure"],

    235: ["&#129392;", "&#128579;"],
    236: ["&#129396;", "&#129395;"],
    237: ["&#128526;", "&#129488;"],
    238: ["&#128557;", "&#128512;"],
    239: ["&#129297;", "&#129312;"],
    240: ["&#128125;", "&#129313;"],
    241: ["&#128148;", "&#128157;"],
    242: ["&#129302;", "&#128123;"],
    243: ["&#128169;", "&#127775;"],
    244: ["&#128170;", "&#129504;"],
    245: ["&#128587;&zwj;&#9794;&#65039;", "&#128581;&zwj;&#9794;&#65039;"],
    246: ["&#128104;&zwj;&#9877;&#65039;", "&#128104;&zwj;&#128295;"],
    247: ["&#128105;&zwj;&#128300;", "&#128105;&zwj;&#127908;"],
    248: ["&#128520;", "&#128519;"],
    249: ["&#129300;", "&#129323;"],
    250: ["&#128024;", "&#128000;"],
    251: ["&#128046;", "&#128055;"],
    252: ["&#128052;", "&#129412;"],
    253: ["&#128041;", "&#128018;"],
    254: ["&#128692;", "&#127947;&#65039;&zwj;&#9794;&#65039;"],
    255: ["&#129338;", "&#127948;"],
    256: ["&#128131;", "&#129493;"],
    257: ["&#129497;", "&#128104;&zwj;&#128640;"],
    258: ["&#128016;", "&#129426;"],
    259: ["&#129415;", "&#128063;"],
    260: ["&#128556;", "&#128527;"],
    261: ["&#129296;", "&#128540;"],
    262: ["&#129315;", "&#128522;"],
    263: ["&#129495;", "&#128716;"],
    264: ["&#129406;", "&#128095;"],
    265: ["&#127913;", "&#129506;"],
    266: ["&#128200;", "&#128201;"],
    267: ["stinky", "fresh"],
    268: ["legit", "scrub"],

    269: ["self-destructive", "self-improving"],
    270: ["French", "Russian"],
    271: ["German", "English"],
    272: ["Italian", "Swedish"],
    273: ["Greek", "Roman"],
    274: ["traumatized", "flourishing"],
    275: ["sturdy", "flimsy"],
    276: ["macho", "metrosexual"],
    277: ["claustrophobic", "spelunker"],
    278: ["offended", "chill"],
    279: ["rhythmic", "stuttering"],
    280: ["musical", "off-key"],
    281: ["lost", "enlightened"],
    282: ["masochistic", "pain-avoidant"],
    283: ["efficient", "overprepared"],
    284: ["oppressed", "privileged"],
    285: ["sunny", "gloomy"],
    286: ["vegan", "cannibal"],
    287: ["loveable", "punchable"],
    288: ["slow-talking", "fast-talking"],
    289: ["believable", "poorly-written"],
    290: ["vibrant", "geriatric"],
    291: ["consistent", "variable"],
    292: ["dispassionate", "romantic"],
    293: ["linear", "circular"],
    294: ["intense", "lighthearted"],
    295: ["knowledgeable", "ignorant"],
    296: ["fixable", "unfixable"],
    297: ["exuberant", "subdued"],
    298: ["secretive", "open-book"],
    299: ["perceptive", "unobservant"],
    300: ["folksy", "presidential"],
    301: ["corporate", "freelance"],
    302: ["sleepy", "frenzied"],
    303: ["loose", "tight"],
    304: ["narcissistic", "low self esteem"],
    305: ["poetic", "factual"],
    306: ["melee", "ranged"],
    307: ["giggling", "chortling"],
    308: ["whippersnapper", "sage"],
    309: ["tailor", "blacksmith"],
    310: ["hunter", "gatherer"],
    311: ["experimental", "reliable"],
    312: ["moist", "dry"],
    313: ["trolling", "triggered"],
    314: ["tattle-tale", "f***-the-police"],
    315: ["punk rock", "preppy"],

    316: ["realistic", "fantastical"],
    317: ["trendy", "vintage"],
    318: ["factual", "exaggerating"],
    319: ["good-cook", "bad-cook"],
    320: ["comedic", "dramatic"],
    321: ["OCD", "ADHD"],
    322: ["interrupting", "attentive"],
    323: ["exhibitionist", "bashful"],
    324: ["badass", "weakass"],
    325: ["gamer", "non-gamer"],
    326: ["random", "pointed"],
    327: ["epic", "deep"],
    328: ["serene", "pensive"],
    329: ["bored", "interested"],
    330: ["envious", "prideful"],
    331: ["ironic", "profound"],
    332: ["sexual", "asexual"],
    333: ["&#129397;", "&#129398;"],
    334: ["&#127875;", "&#128128;"],
    335: ["&#127936;", "&#127912;"],
    336: ["clean", "perverted"],
    337: ["empath", "psychopath"],
    338: ["haunted", "blissful"],
    339: ["entitled", "grateful"],
    340: ["ambitious", "realistic"],
    341: ["stuck-in-the-past", "forward-thinking"],
    342: ["fire", "water"],
    343: ["earth", "air"],
    344: ["lover", "fighter"],
    345: ["overachiever", "underachiever"],
    346: ["Coke", "Pepsi"],
    347: ["twitchy", "still"],
    348: ["freak", "normie"],
    349: ["thinker", "doer"],
    350: ["hard-work", "natural-talent"],
    351: ["stingy", "generous"],
    352: ["stubborn", "accommodating"],
    353: ["extravagant", "thrifty"],
    354: ["demanding", "unchallenging"],
    355: ["two-faced", "one-faced"],
    356: ["plastic", "wooden"],
    357: ["neutral", "opinionated"],
    358: ["chivalrous", "businesslike"],
    359: ["high standards", "desperate"],
    360: ["on-time", "tardy"],

    361: ["everyman", "chosen one"],
    362: ["jealous", "opinionated"],
    363: ["protagonist", "antagonist"],
    364: ["devoted", "unfaithful"],
    365: ["fearmongering", "reassuring"],
    366: ["common sense", "analysis"],
    367: ["unemotional", "emotional"],
    368: ["rap", "rock"],
    369: ["genocidal", "not genocidal"],
    370: ["cat person", "dog person"],
    371: ["indie", "pop"],
    372: ["cultured", "rustic"],
    373: ["tautology", "oxymoron"],
    374: ["bad boy", "white knight"],
    375: ["princess", "queen"],
    376: ["hypochondriac", "stoic"],
    377: ["yes-man", "contrarian"],
    378: ["giving", "receiving"],
    379: ["chic", "cheesy"],
    380: ["celebrity", "boy/girl-next-door"],

    381: ["goth", "flower child"],
    382: ["summer", "winter"],
    383: ["frank", "sugarcoated"],
    384: ["naive", "paranoid"],
    385: ["gullible", "cynical"],
    386: ["motivated", "unmotivated"],
    387: ["radical", "centrist"],
    388: ["monotone", "expressive"],
    389: ["love-focused", "money-focused"],
    390: ["transparent", "machiavellian"],
    391: ["timid", "cocky"],
    392: ["concise", "long-winded"],
    393: ["picky", "always down"],
    394: ["proactive", "reactive"],
    395: ["prudish", "flirtatious"],
    396: ["innocent", "jaded"],
    397: ["touchy-feely", "distant"],
    398: ["muddy", "washed"],
    399: ["quirky", "predictable"],
    400: ["never cries", "often crying"],

    /*
    
    brainstorm
    
    401 : ["stereotypical","boundary breaking"],
    402 : ["original","clich&#xE9;"],
    403 : ["hugs","handshakes"],
    404 : ["homebody","world traveler"],
    405 : ["naughty","nice"],
    406 : ["junkie","straight edge"],
    407 : ["small-vocabulary","big-vocabulary"],
    408 : ["dystopian","utopian"],
    409 : ["parental","childlike"],
    410 : ["writer","reader"],
    411 : ["creator","consumer"],
    412 : ["capitalist","communist"],
    413 : ["positive","negative"],
    414 : ["grounded","fantasy-prone"],
    415 : ["thinker","feeler"],
    416 : ["intuitive","observant"],
    417 : ["judging","perceiving"],
    418 : ["proud","apologetic"],
    419 : ["bubbly","flat"],
    420 : ["tired","wired"],
    421 : ["woke","problematic"],
    422 : ["grumpy","cheery"],
    423 : ["hippie","militaristic"],
    424 : ["gluttonous","moderate"],
    425 : ["flawed","perfect"],
    
    */
};